#!/bin/bash
# HCP GitHub Issue Creation Script
# Generated by the Orchestrator agent (Claude Opus 4.6) on 2026-02-22
# Run after: gh auth login
#
# Note: These issues were organized by an AI agent because its human
# asked it to look after project management so his head didn't melt.
# A human reviewer/maintainer for the issue tracker would be very welcome!
#
# Repo: Human-Cognome-Project/human-cognome-project

REPO="Human-Cognome-Project/human-cognome-project"

echo "=== Creating labels ==="

gh label create "engine" --description "O3DE + PhysX 5 engine work" --color "0052CC" --repo "$REPO" 2>/dev/null || echo "label 'engine' exists"
gh label create "database" --description "PostgreSQL schema, migrations, LMDB cache" --color "5319E7" --repo "$REPO" 2>/dev/null || echo "label 'database' exists"
gh label create "linguistics" --description "Force definitions, sub-categorization, conceptual mesh" --color "D93F0B" --repo "$REPO" 2>/dev/null || echo "label 'linguistics' exists"
gh label create "infrastructure" --description "Build systems, CI/CD, environments, tooling" --color "006B75" --repo "$REPO" 2>/dev/null || echo "label 'infrastructure' exists"
gh label create "librarian" --description "Entity cataloging, text ingestion pipeline" --color "FBCA04" --repo "$REPO" 2>/dev/null || echo "label 'librarian' exists"
gh label create "python-tools" --description "Reference implementations and tooling in src/hcp/" --color "3572A5" --repo "$REPO" 2>/dev/null || echo "label 'python-tools' exists"
gh label create "documentation" --description "Docs, specs, guides" --color "0075CA" --repo "$REPO" 2>/dev/null || echo "label 'documentation' exists"
gh label create "good first issue" --description "Good for newcomers" --color "7057FF" --repo "$REPO" 2>/dev/null || echo "label 'good first issue' exists"
gh label create "agent-suitable" --description "Well-suited for AI agent contributors" --color "B60205" --repo "$REPO" 2>/dev/null || echo "label 'agent-suitable' exists"
gh label create "phase-1" --description "Phase 1: Document Processing Workstation" --color "C2E0C6" --repo "$REPO" 2>/dev/null || echo "label 'phase-1' exists"
gh label create "phase-2" --description "Phase 2: Boilerplate and Comparison" --color "C2E0C6" --repo "$REPO" 2>/dev/null || echo "label 'phase-2' exists"
gh label create "cleanup" --description "Debt, drift, stale references" --color "EDEDED" --repo "$REPO" 2>/dev/null || echo "label 'cleanup' exists"
gh label create "contributor-path" --description "Clear entry point for new contributors" --color "0E8A16" --repo "$REPO" 2>/dev/null || echo "label 'contributor-path' exists"

echo ""
echo "=== Creating milestones ==="

gh api repos/$REPO/milestones -f title="Phase 1: Document Processing Workstation" -f description="Encode Gutenberg texts into PBM storage. Validate lossless round-trip." -f state="open" 2>/dev/null || echo "milestone exists"
gh api repos/$REPO/milestones -f title="Phase 2: Boilerplate and Comparison" -f description="Document comparison, boilerplate detection, sub-PBM compression." -f state="open" 2>/dev/null || echo "milestone exists"
gh api repos/$REPO/milestones -f title="Documentation Alignment" -f description="Fix doc drift, update stale references, align specs with current architecture." -f state="open" 2>/dev/null || echo "milestone exists"

echo ""
echo "=== Creating issues ==="

# --- ENGINE: Phase 1 ---

gh issue create --repo "$REPO" \
  --title "Create HCPDocumentBuilder skeleton" \
  --label "engine,phase-1" \
  --body "$(cat <<'EOF'
## Summary
Create the HCPDocumentBuilder class that integrates with O3DE's Asset Processor for document ingestion.

**Location:** `hcp-engine/Gem/Source/`
**References:** `hcp-engine/ROADMAP.md` Phase 1, `docs/research/source-workstation-design.md`

## Status
READY — no blockers.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: HCPDocumentBuilder"

gh issue create --repo "$REPO" \
  --title "Create HCPDocumentBuilderVocab (Postgres-backed)" \
  --label "engine,phase-1" \
  --body "$(cat <<'EOF'
## Summary
Build-time vocabulary access backed by Postgres (vs runtime LMDB). Needed for the Asset Processor builder pipeline.

**Location:** `hcp-engine/Gem/Source/`
**References:** `hcp-engine/AGENTS.md` Module Boundaries table

## Status
READY — no blockers.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: BuilderVocab"

gh issue create --repo "$REPO" \
  --title "Persist bond tables as files in engine area" \
  --label "engine,phase-1" \
  --body "$(cat <<'EOF'
## Summary
Bond compiler currently recomputes char→word (5,409 pairs) and byte→char (1,976 pairs) from Postgres on every engine startup (~3.1s + ~37ms). These should be persisted as files in the engine area and loaded from disk, with a recompile flag when vocabulary changes.

**Location:** `hcp-engine/Gem/Source/HCPBondCompiler.h/.cpp`
**Current behavior:** Queries Postgres on every `Activate()`
**Desired:** Load from file, recompute only when flagged

## Status
READY — Patrick approved storing in engine area.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: bond tables"

gh issue create --repo "$REPO" \
  --title "Test detection scene with larger texts" \
  --label "engine,phase-1" \
  --body "$(cat <<'EOF'
## Summary
Physics detection scene works on "the cat sat on the mat" (11 clusters, 131ms). Needs testing with:
1. Yellow Wallpaper (52KB) — current self-test target
2. Gutenberg books (100KB+)

Track performance, accuracy, and any convergence issues at scale.

**Location:** `hcp-engine/Gem/Source/HCPDetectionScene.h/.cpp`

## Status
READY — detection scene is working.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: larger texts"

gh issue create --repo "$REPO" \
  --title "Add .Builders CMake target and hcpengine_builder_files.cmake" \
  --label "engine,phase-1,infrastructure" \
  --body "$(cat <<'EOF'
## Summary
Separate CMake target for Asset Processor builders (document ingestion). Needed for the source workstation pipeline.

**Location:** `hcp-engine/Gem/`
**References:** `hcp-engine/TODO.md`, `hcp-engine/AGENTS.md` "Adding Format Builders"

## Status
READY — no blockers.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: builders cmake"

# --- DATABASE ---

gh issue create --repo "$REPO" \
  --title "Fix marker table PK collision (add t_p5 column)" \
  --label "database,good first issue" \
  --body "$(cat <<'EOF'
## Summary
Control tokens in the marker table share `(t_p3, t_p4)` combinations, causing PK collisions. The table needs a `t_p5` column added to disambiguate.

**Location:** Relevant migration in `db/migrations/`
**Test:** A Pail of Air ingestion (8,901 tokens)

## Status
READY — straightforward schema change.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: marker pk"

gh issue create --repo "$REPO" \
  --title "Update boilerplate loading: remove forward walk" \
  --label "database,phase-1" \
  --body "$(cat <<'EOF'
## Summary
Boilerplate detection is moving from forward walk / CheckContinuation / boolean loop to physics-based rigid body detection. Postgres should push boilerplate sequences into LMDB alongside word lookups on cache miss (piggyback on word handler).

**What to remove:** Forward walk mechanism, forward sub-db
**What to add:** Boilerplate push on word cache miss, hot index of what's been pushed
**References:** `docs/research/continuation-index-design.md` (being revised), `hcp-engine/docs/db-specialist-pbm-storage.md`

## Status
READY — design direction confirmed with Patrick.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: boilerplate"

gh issue create --repo "$REPO" \
  --title "Design LMDB purge strategy" \
  --label "database" \
  --body "$(cat <<'EOF'
## Summary
LMDB persists across documents (no wipe between runs). A background Python process is needed to monitor LMDB environments and purge stale entries. LMDB has no built-in eviction — application-layer LRU policy with per-environment `map_size` cap.

**Considerations:**
- Multiple concurrent envelopes
- Purge vs rebuild tradeoffs
- Memory pressure monitoring

## Status
Design needed — no implementation yet.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: lmdb purge"

# --- DOCUMENTATION ---

gh issue create --repo "$REPO" \
  --title "Update docs/status.md to current state" \
  --label "documentation,cleanup,good first issue,agent-suitable" \
  --body "$(cat <<'EOF'
## Summary
`docs/status.md` was last updated 2026-02-05 and doesn't reflect:
- O3DE + PhysX 5 as the engine (confirmed, working prototype)
- PBM prefix tree storage (migration 011)
- Self-filling LMDB cache (7 sub-dbs, plain UTF-8)
- Var system (migration 010)
- Entity databases populated (573 fiction, 70 NF entities)
- Bond compiler and detection scene (working)
- 16 commits of new work since Feb 17

**References:** Current state documented in `ROADMAP.md`, `hcp-engine/ROADMAP.md`

## Status
READY — good first issue for anyone wanting to understand the project.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: status.md"

gh issue create --repo "$REPO" \
  --title "Purge stale OpenMM/Godot references from docs" \
  --label "documentation,cleanup,agent-suitable" \
  --body "$(cat <<'EOF'
## Summary
Several docs still reference OpenMM or Godot as engine candidates. The engine is confirmed as O3DE + PhysX 5. Known stale areas:
- `docs/roadmap.md` — "Which physics engine?" is answered
- `docs/spec/pair-bond-maps.md` — may reference OpenMM
- Various research docs in `docs/research/`
- Root `AGENTS.md` — "Survey physics engines (Godot, Rapier, OpenMM, Taichi)" in task list
- "7 force types" references anywhere — that was an OpenMM artifact, we define our own forces

**Do NOT delete research docs** — they document the evaluation process. Just ensure they're clearly marked as historical/evaluation, not current architecture.

## Status
READY — grep for "OpenMM", "Godot", "7 force types" across docs/.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: stale refs"

gh issue create --repo "$REPO" \
  --title "Update docs/roadmap.md open questions" \
  --label "documentation,cleanup,good first issue" \
  --body "$(cat <<'EOF'
## Summary
`docs/roadmap.md` lists open questions that have been answered:
- "Which physics engine?" → O3DE + PhysX 5 (confirmed, working)
- "How are conceptual forces quantified?" → Linguistics-driven, ~65 core forces (categorization TBD)
- "What is the right granularity for LoD levels?" → Hierarchical: bytes → chars → words → sequences → topics

Update to reflect answered questions and add any new open questions from current work.

## Status
READY.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: roadmap open q"

# --- CONTRIBUTOR PATHS ---

gh issue create --repo "$REPO" \
  --title "Format builder: PDF text extractor" \
  --label "contributor-path,python-tools,good first issue" \
  --body "$(cat <<'EOF'
## Summary
Create a PDF text extractor that feeds into the existing tokenizer pipeline. This is one of several format builders needed for the Source Workstation.

**Pattern:** Extract plain text → feed to existing tokenizer → store via existing storage module
**Tool:** `pdftotext` (already installed) or Python library
**Template:** See `hcp-engine/AGENTS.md` "Adding Format Builders" section
**Output location:** `src/hcp/ingest/` or as an O3DE Asset Builder

## Why this matters
Currently we can only process plain text files. PDF support opens up a huge corpus of documents.

## Status
READY — clear pattern to follow, existing pipeline handles everything after text extraction.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: pdf builder"

gh issue create --repo "$REPO" \
  --title "Format builder: EPUB text extractor" \
  --label "contributor-path,python-tools,good first issue" \
  --body "$(cat <<'EOF'
## Summary
Create an EPUB text extractor. EPUB is ZIP + XHTML — extract text content, feed to existing tokenizer pipeline.

**Pattern:** Extract plain text → feed to existing tokenizer → store via existing storage module
**Template:** See `hcp-engine/AGENTS.md` "Adding Format Builders" section

## Status
READY — clear pattern to follow.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: epub builder"

gh issue create --repo "$REPO" \
  --title "Format builder: HTML text extractor" \
  --label "contributor-path,python-tools,good first issue" \
  --body "$(cat <<'EOF'
## Summary
Create an HTML text extractor. Strip tags, preserve meaningful structure (paragraphs, headings), feed to existing tokenizer pipeline.

**Pattern:** Extract plain text → feed to existing tokenizer → store via existing storage module
**Template:** See `hcp-engine/AGENTS.md` "Adding Format Builders" section

## Status
READY — clear pattern to follow.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: html builder"

gh issue create --repo "$REPO" \
  --title "Format builder: Markdown text extractor" \
  --label "contributor-path,python-tools,good first issue" \
  --body "$(cat <<'EOF'
## Summary
Create a Markdown text extractor. Minimal parsing needed — Markdown is close to plain text already. Feed to existing tokenizer pipeline.

**Pattern:** Extract plain text → feed to existing tokenizer → store via existing storage module
**Template:** See `hcp-engine/AGENTS.md` "Adding Format Builders" section

## Status
READY — simplest of the format builders.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: markdown builder"

gh issue create --repo "$REPO" \
  --title "Format builder: Wikipedia dump processor" \
  --label "contributor-path,python-tools" \
  --body "$(cat <<'EOF'
## Summary
Create a Wikipedia dump processor. Stream XML dump files, extract article text, feed to existing tokenizer pipeline. Larger scope than other format builders due to dump size and structure.

**Pattern:** XML streaming → text extraction → existing tokenizer → existing storage
**Template:** See `hcp-engine/AGENTS.md` "Adding Format Builders" section

## Status
READY — clear pattern, medium difficulty due to XML streaming at scale.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: wikipedia builder"

gh issue create --repo "$REPO" \
  --title "SQLite vocabulary backend" \
  --label "infrastructure,contributor-path" \
  --body "$(cat <<'EOF'
## Summary
Portable vocabulary backend using SQLite instead of PostgreSQL. Enables standalone tools and the "Token ID only" download tier where users assemble their own local database.

**Design:** Same schema pattern as Postgres, switchable via flag. See `hcp-engine/ROADMAP.md` and `docs/research/source-workstation-design.md` for the three data models (full download, custom assembly, core only).

## Status
READY — schema pattern is well-defined, needs implementation.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: sqlite"

gh issue create --repo "$REPO" \
  --title "Remove socket server once Asset Builder is proven" \
  --label "engine,cleanup" \
  --body "$(cat <<'EOF'
## Summary
`HCPSocketServer.h/.cpp` (TCP on port 9720) was scaffolding for the early pipeline. Once the O3DE Asset Builder pathway is proven for document ingestion, the socket server can be removed.

**Location:** `hcp-engine/Gem/Source/HCPSocketServer.h/.cpp`
**Blocked by:** Asset Builder proving out (Phase 1)

## Status
BLOCKED — waiting for Asset Builder to be functional.

---
*This issue was created by the Orchestrator agent (Claude Opus 4.6) on behalf of its human, who asked it to organize the issue tracker so his head didn't melt. A human reviewer/maintainer for these issues would be very welcome!*
EOF
)" || echo "FAILED: socket server"

gh issue create --repo "$REPO" \
  --title "Seeking: Human issue tracker maintainer" \
  --label "infrastructure,good first issue" \
  --body "$(cat <<'EOF'
## Summary
These issues were batch-created by the project's Orchestrator agent (Claude Opus 4.6) because its human needed the project management organized and couldn't context-switch into GitHub's UI without derailing the technical work.

**We'd love a human reviewer/maintainer for the issue tracker.** Someone who can:
- Triage new issues
- Keep labels and milestones organized
- Close issues that get resolved via commits
- Add context or clarify requirements
- Link related issues

The project has a small but growing community (watchers, forks, stars) and several external collaborators doing deep dives. A human touch on project management would make a real difference.

**About the project:** HCP models cognition as physics — tokens as particles, bonds as forces, physics engines as inference engines. We're currently building the document processing workstation using O3DE + PhysX 5. See `ROADMAP.md` for the full picture.

No prior physics or linguistics knowledge required — just GitHub project management skills and curiosity.

---
*Created by Claude Opus 4.6, the project's orchestrator agent. Yes, an AI is asking for human help with project management. The irony is not lost on us.*
EOF
)" || echo "FAILED: maintainer"

echo ""
echo "=== Done! ==="
echo "Created labels, milestones, and issues."
echo "Run 'gh issue list --repo $REPO' to verify."
